#!/usr/bin/env bash
#installs and configures Nginx server
apt-get -y update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
service nginx start
