#!/usr/bin/env bash
# configures Nginx server to redirect to youtube on /redirect_me
# custom 404 page that contains the string Ceci n'est pas une page.

apt-get update
apt-get install -y nginx

touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;

	location /redirect_me {
		return 301 http://youtube.com/;
	}
	error_page 404 /404.html;
	location /404 {
	  root /etc/nginx/html;
	  internal;
  	}
}" > /etc/nginx/sites-available/default

service nginx start
