#!/usr/bin/env bash
# isntall and configures HAProxy

sudo apt-get update
sudo apt-get install haproxy -y

config_details="
frontend haproxy-1
    bind *:80
    mode http
    default_backend server_group1

backend server_group1
    balance roundrobin
    server 47932-web-01 54.167.86.129:80 check
    server 47932-web-02 18.234.80.6:80   check
"
sudo chown -R "$USER":"$USER" /etc/haproxy/
echo "$config_details" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
