#!/usr/bin/env bash
# Creates a file /var/run/myscript.pid containing the script PID.
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" when receiving a SIGTERM
# Displays "Y U no love me?!" when receiving a SIGINT
# Deletes the file /var/run/myscript.pid and terminates upon receiving a SIGQUIT or SIGTERM.

clean() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && clean' SIGTERM
  trap 'clean' SIGQUmT
done
