#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
# a 2 sec sleep and Displays "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2 
  trap 'echo "I am invincible!!!"' SIGTERM 
done
