#!/usr/bin/env bash
#configure nginx to run as nginx users and listen on port 8080
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx/*                                                                                         
chmod 700 /etc/nginx/nginx.conf
service nginx reload
service nginx restart
