#!/usr/bin/env bash
#configure nginx to run as nginx users and listen on port 8080
pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chown 755 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
